*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZGCMV_PROJH_1...................................*
FORM GET_DATA_ZGCMV_PROJH_1.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZGCPROJH_1 WHERE
(VIM_WHERETAB) .
    CLEAR ZGCMV_PROJH_1 .
ZGCMV_PROJH_1-CLIENTNUMBER =
ZGCPROJH_1-CLIENTNUMBER .
ZGCMV_PROJH_1-PROJECTNUMBER =
ZGCPROJH_1-PROJECTNUMBER .
    SELECT SINGLE * FROM ZGCPROJH_2 WHERE
PROJECTNUMBER = ZGCPROJH_1-PROJECTNUMBER .
    IF SY-SUBRC EQ 0.
ZGCMV_PROJH_1-PROJECTDESC =
ZGCPROJH_2-PROJECTDESC .
ZGCMV_PROJH_1-PROJECTLOCATION =
ZGCPROJH_2-PROJECTLOCATION .
    ENDIF.
<VIM_TOTAL_STRUC> = ZGCMV_PROJH_1.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZGCMV_PROJH_1 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZGCMV_PROJH_1.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZGCMV_PROJH_1-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZGCPROJH_1 WHERE
  PROJECTNUMBER = ZGCMV_PROJH_1-PROJECTNUMBER .
    IF SY-SUBRC = 0.
    DELETE ZGCPROJH_1 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZGCPROJH_2 WHERE
    PROJECTNUMBER = ZGCPROJH_1-PROJECTNUMBER .
    IF SY-SUBRC = 0.
    DELETE ZGCPROJH_2 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZGCPROJH_1 WHERE
  PROJECTNUMBER = ZGCMV_PROJH_1-PROJECTNUMBER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZGCPROJH_1.
    ENDIF.
ZGCPROJH_1-CLIENTNUMBER =
ZGCMV_PROJH_1-CLIENTNUMBER .
ZGCPROJH_1-PROJECTNUMBER =
ZGCMV_PROJH_1-PROJECTNUMBER .
    IF SY-SUBRC = 0.
    UPDATE ZGCPROJH_1 ##WARN_OK.
    ELSE.
    INSERT ZGCPROJH_1 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZGCPROJH_2 WHERE
    PROJECTNUMBER = ZGCPROJH_1-PROJECTNUMBER .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZGCPROJH_2.
ZGCPROJH_2-PROJECTNUMBER =
ZGCPROJH_1-PROJECTNUMBER .
      ENDIF.
ZGCPROJH_2-PROJECTDESC =
ZGCMV_PROJH_1-PROJECTDESC .
ZGCPROJH_2-PROJECTLOCATION =
ZGCMV_PROJH_1-PROJECTLOCATION .
    IF SY-SUBRC = 0.
    UPDATE ZGCPROJH_2 ##WARN_OK.
    ELSE.
    INSERT ZGCPROJH_2 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZGCMV_PROJH_1-UPD_FLAG,
STATUS_ZGCMV_PROJH_1-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZGCMV_PROJH_1.
  SELECT SINGLE * FROM ZGCPROJH_1 WHERE
PROJECTNUMBER = ZGCMV_PROJH_1-PROJECTNUMBER .
ZGCMV_PROJH_1-CLIENTNUMBER =
ZGCPROJH_1-CLIENTNUMBER .
ZGCMV_PROJH_1-PROJECTNUMBER =
ZGCPROJH_1-PROJECTNUMBER .
    SELECT SINGLE * FROM ZGCPROJH_2 WHERE
PROJECTNUMBER = ZGCPROJH_1-PROJECTNUMBER .
    IF SY-SUBRC EQ 0.
ZGCMV_PROJH_1-PROJECTDESC =
ZGCPROJH_2-PROJECTDESC .
ZGCMV_PROJH_1-PROJECTLOCATION =
ZGCPROJH_2-PROJECTLOCATION .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZGCMV_PROJH_1-PROJECTDESC .
      CLEAR ZGCMV_PROJH_1-PROJECTLOCATION .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZGCMV_PROJH_1 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZGCMV_PROJH_1-PROJECTNUMBER TO
ZGCPROJH_1-PROJECTNUMBER .
MOVE ZGCMV_PROJH_1-CLIENTNUMBER TO
ZGCPROJH_1-CLIENTNUMBER .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZGCPROJH_1'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZGCPROJH_1 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZGCPROJH_1'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZGCPROJH_1-PROJECTNUMBER TO
ZGCPROJH_2-PROJECTNUMBER .
MOVE ZGCMV_PROJH_1-CLIENTNUMBER TO
ZGCPROJH_2-CLIENTNUMBER .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZGCPROJH_2'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZGCPROJH_2 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZGCPROJH_2'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
